sudo: required
dist: trusty
addons:
  apt:
    packages:
    - texlive-xetex
    - texlive-latex-extra
    - lmodern
    - texlive-latex-recommended
    - xzdec
    - texlive-fonts-recommended
script:
- tlmgr init-usertree
- tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
- tlmgr update --all
- tlmgr install etoolbox tcolorbox framed polyglossia hyperref pgf xcolor
- xelatex bsz2.tex
- xelatex bsz2.tex
deploy:
  provider: releases
  api_key:
    secure: ucVvDZmEaB7YveR/5cOI1tgT1jolA8+0ynyPRjVZgVqnSJ0+TwmxL20yw+q2Zsu6KyDhorTSpfcpK7OA1Hn/rjVCg2XQc/8IwgiHoOWPiLyzHSdytqCvfbsw4SOwcM5oHiN0CTsUAZfEJGUTtTDgofyKwkndWsKhBhqn1xnzoYgpa6KxVtS66p+Cq8BnX2fmq8FxuHuEPNo/B/C7BZSzrCnpcfTfvn+/92bWBxwnQkGDnNI4oNmt9jwx0HvRfxkjpP5MhzKwPixhxjxl6n6hAU8+ynYtN7XQAqG/X5X5ymBtMqSFZcrGdd0YA2USrMt38fLsBOoM8DYIR+8FYCUE/UIBSIOhACHBV5Wq4Y/Q0Jf0WH4luoMvVZJit2SydwNv2AwZuuOXXedg+kdYjLl1AhbDya2igE0+VZeQf7H/RaBjR9glSJ13/wQ49OZezw86JAkSGfrJwml9B3wXkFu3W6jU5XgDU4r0SOK2MavIbYArQCe04nwKsGh5qa4cyVKBNyt4Jit59AURJ4QuELY9tu83rscra0Ma3M02epZueX1XLxIGmxr3IvTEHdikpAxmwkrL1fxFXAZjlYfRJxm3q3BzFmj61h8SYRwDE+g92HjSl8s0x/EY/tmvg4rW+3lS6buFrDixfhO77ODFctdrkfmY1CZhf04oYu1zS85ZcJs=
  file: bsz2.pdf
  skip-cleanup: true
  overwrite: true
  on:
    repo: bme-notes/bsz2
