sudo: required
dist: trusty
addons:
  apt_packages:
   - texlive-xetex
   - texlive-latex-extra
   - lmodern
   - texlive-latex-recommended
   - xzdec
   - texlive-fonts-recommended
script:
 - tlmgr init-usertree
 - tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
 - tlmgr update --all
 - tlmgr install etoolbox tcolorbox framed polyglossia hyperref pgf xcolor
 - xelatex bsz2.tex
 - xelatex bsz2.tex
deploy:
  provider: releases
  api_key:
    secure: 06SL24hU7iulE+V6QUqzzvxPJMTMR5gvGp/lEbktvs4KAsJFgVcTnUN2YpVgD57R9RoqiFcPXU2rDZ7o7DAsufHln+ASJVpGmB5cRrl7ZzF5GD/2VQ6MzPJI7B+uw3r5bk+pdZsyTeGnJAelihm/u688v1Yyq7A8R6ne0egx0WwGwq46MSIssqxB2HeqpYmKEnRHWbc9ZPDJgQVArxNO9rNG6PTo1gVqQajRxxGKaHcjCRBiY6O/08clMd7kZqJVHdPKDn0/r5yRjGnup+NCxGAc8SvctlTd1IAd0BC9TKoO4XO4h56AZAJjSpvNfzQj6AKguvmwr3Lx56m8mzIgR/Edmip7m06sS9vX3Jp3WLxkAf9Tn8VkuvjPXVee9pQUtrjmvNSgvCJ3bfqlCuiv9v77fHdFQlStbXhDEKPNBgb10XwteE2/vvc6U1F0KUxbOUhFJ9ZK25VQ7/fJK9wFB5FCbAywdvaVhhIsGgtIy4RmqFbN3pHLb2eCzspfwiS7Q61/SXa60wV95glSG8LJqcDFaqxfMvxX8Kdioy/zYb0BCdEj1NZaYAKsXgdCJ6yzd2pYOlIUyKqOAysybb0SlSZrQ7yYMiCwSkWtH7ZdnTa+OFWkjth9cSmGdkUHsU3ger/Xn2SIICK74+xTKFaGq345v9U8KAbrNxLbk9L9cV4=
  file: bsz2.pdf
  skip-cleanup: true
  overwrite: true
  on:
    repo: bme-notes/bsz2
